definitions:
  room:
    properties:
      active:
        type: boolean
      address:
        type: string
      create_tx_hash:
        type: string
      description:
        type: string
      event_code:
        type: string
      id:
        type: integer
      is_private:
        type: boolean
      owner_address:
        type: string
      owner_id:
        type: integer
      title:
        type: string
      wei_balance:
        type: integer
      wei_prize:
        type: integer
    type: object
info:
  contact: {}
  license: {}
  title: Sample API
  version: 1.0.0
paths:
  /rooms:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/room'
            type: array
      summary: ルーム情報を取得します
      tags:
      - Room
swagger: "2.0"
